### ISSUE TITLE
State files not always produced

### ISSUE THREAD

**Issue by rbouckaert** [nicfel/CoupledMCMC#12] opened 2020-07-01 23:24 UTC
Some times, only the 0state and 3state files are produced, sometimes none at all in a 4 chain run.

When this happens, it seems to happen consistently.

One observation is that this is correlated to when `storeEvery` and `resampleEvery` in the run element differ: making them the same seems to fix the problem. 

Not sure how to fix this as yet.

**Comment by nicfel** [comment] 2020-07-02 16:42
Was caused by a scheduling error when I introduced neighbour only swapping. The error is fixed in this commit https://github.com/nicfel/CoupledMCMC/commit/aae9aef38b8bb3af85e5f38c9fbb59a84e0567c1

**Closed by nicfel** 2020-07-02 16:42 UTC
